version: "3.10"
services:
  worker:
    build: .
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - MAIN_GROUP_ID=${MAIN_GROUP_ID}
      - DEV_ID=${DEV_ID}
      - TELEGRAPH_TOKEN =${TELEGRAPH_TOKEN } 
